### ISSUE TITLE
Avances de las vistas del prototipo

### ISSUE THREAD

**Issue by nihilarion** [ISWPOLI/Lavaseco#2]

**Comment by nihilarion** [comment]
se agregan nuevas vistas para incluir el registro de empleados en la nomina y buscar empleados en la lista

**Comment by javaviles** [comment]
se modifica la vista incial y se anade una vista para la aplicacion independiente del sitio web informativo

**Comment by javaviles** [comment]
Modificación del plantilla, adición de nuevos Slides
